import Foundation

// MARK: - In-App Localization (EN / FR)
// Lightweight string table driven by the in-app language setting (not the
// system locale) so switching language in Settings updates the UI live.
// French wording mirrors the web frontend (frontend/i18n/fr.ts).
enum L10n {
    static var language: AppLanguage = .english

    static func t(_ key: String) -> String {
        switch language {
        case .english:
            return en[key] ?? key
        case .french:
            return fr[key] ?? en[key] ?? key
        }
    }

    private static let en: [String: String] = [
        // Common
        "common.cancel": "Cancel",
        "common.delete": "Delete",
        "common.done": "Done",
        "common.add": "Add",
        "common.create": "Create",
        "common.ok": "OK",
        "common.saveChanges": "Save Changes",
        "common.transaction": "transaction",
        "common.transactions": "transactions",
        "common.archivedSuffix": "(Archived)",

        // Tabs / App
        "tab.dashboard": "Dashboard",
        "tab.experiences": "Experiences",
        "tab.settings": "Settings",
        "tab.search": "Search",
        "app.connecting": "Connecting to Tekyida…",
        "app.syncError": "Could not sync",

        // Auth
        "auth.verifyTitle": "Verify your email",
        "auth.welcome": "Welcome to Tekyida",
        "auth.enterCode": "Enter the 6-digit code we sent to %@.",
        "auth.signinSubtitle": "Sign in to sync your notebooks and transactions.",
        "auth.codePlaceholder": "6-digit verification code",
        "auth.verify": "Verify email",
        "auth.resend": "Resend code",
        "auth.backToSignin": "Back to sign in",
        "auth.name": "Name",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.confirmPassword": "Confirm password",
        "auth.createAccount": "Create account",
        "auth.signIn": "Sign in",
        "auth.passwordMismatch": "Passwords do not match.",
        "auth.passwordTooShort": "Password must be at least 8 characters.",
        "auth.haveAccount": "I already have an account",
        "auth.createOne": "Create an account",

        // Dashboard / Contacts
        "contacts.title": "Contacts",
        "contacts.emptyTitle": "No Contacts Yet",
        "contacts.emptySubtitle": "Add your first contact to track money owed or lent.",
        "contacts.add": "Add Contact",
        "contacts.deleteTitle": "Delete Contact?",
        "contacts.deleteMessage": "Deleting '%@' will remove all their direct transactions.",
        "contact.new": "New Contact",
        "contact.edit": "Edit Contact",
        "contact.namePlaceholder": "Full Name (e.g. Sarah Smith)",
        "contact.phonePlaceholder": "Phone (optional)",
        "contact.save": "Save Contact",
        "contact.update": "Update Contact",
        "timeline.title": "Activity Timeline",
        "timeline.emptyTitle": "No Transactions Yet",
        "timeline.emptySubtitle": "Tap the button below to add your first transaction.",

        // Stats
        "stats.moneyOwed": "Money Owed",
        "stats.moneyGiven": "Money Given",
        "stats.netBalance": "Net Balance",

        // Transactions
        "transaction.direction": "Direction",
        "transaction.add": "Add Transaction",
        "transaction.theyOweYou": "They owe you",
        "transaction.youOweThem": "You owe them",
        "transaction.amountPlaceholder": "Amount (e.g. 150)",
        "transaction.descriptionPlaceholder": "Description (optional)",
        "transaction.notePlaceholder": "Note or description",
        "transaction.date": "Date",
        "transaction.dateAndTime": "Date & Time",
        "transaction.edit": "Edit Transaction",
        "transaction.deleteTitle": "Delete Transaction?",

        // Experiences
        "experiences.title": "Experiences",
        "filter.all": "All",
        "filter.active": "Active",
        "filter.closed": "Closed",
        "experiences.openTotal": "Open Experiences Total",
        "experiences.emptyTitle": "No Experiences Found",
        "experiences.emptySubtitle": "Group expenses and split bills with friends using experiences.",
        "experiences.add": "Add Experience",
        "experiences.deleteTitle": "Delete Experience?",
        "experiences.deleteMessage": "Deleting '%@' will remove all its transactions.",
        "experience.new": "New Experience",
        "experience.edit": "Edit Experience",
        "experience.namePlaceholder": "Experience Name (e.g. Summer Vacation)",
        "experience.linkedContact": "Linked Contact",
        "experience.noContact": "None (Standalone Experience)",
        "experience.save": "Save Experience",
        "experience.update": "Update Experience",
        "experience.statusClosed": "Closed",
        "experience.statusOpen": "Open",
        "experience.closedNotice": "This experience is closed. Reopen it to make changes.",
        "experience.transactionsTitle": "Transactions",
        "experience.emptyTitle": "No Transactions in this Experience",
        "experience.emptySubtitle": "Tap the button below to add expenses or payments to this experience.",

        // Transfer
        "transfer.title": "Transfer Experience",
        "transfer.subtitle": "Move to another notebook",
        "transfer.detail": "Moving this experience will transfer all associated transactions. Contacts are notebook-scoped, so any contact link will be detached.",
        "transfer.noOthers": "No other notebooks found. Create another notebook first.",
        "transfer.target": "Target Notebook",
        "transfer.selectDestination": "Select Destination",
        "transfer.confirm": "Confirm Transfer",
        "transfer.transfer": "Transfer",

        // Notebooks
        "notebooks.title": "Notebooks",
        "notebooks.activeSection": "Active Notebooks",
        "notebooks.archivedSection": "Archived Notebooks",
        "notebooks.namePlaceholder": "Notebook Name (max 20)",
        "notebooks.new": "New Notebook",
        "notebooks.showArchived": "Show Archived (%d)",
        "notebooks.hideArchived": "Hide Archived (%d)",
        "notebooks.deleteTitle": "Delete Notebook?",
        "notebooks.deleteMessage": "This will permanently delete '%@' and all its contacts, experiences, and transactions.",
        "notebook.editTitle": "Edit Notebook",
        "notebook.nameField": "Notebook name",
        "notebook.charLimit": "Notebook names can be up to 20 characters.",
        "notebook.manage": "Manage Notebooks",
        "notebook.select": "Select Notebook",

        // Sync
        "sync.syncing": "Syncing",
        "sync.offline": "Offline",
        "sync.pendingCount": "%d pending sync",
        "sync.bannerSyncing": "Syncing offline changes…",
        "sync.bannerOffline": "Offline. Changes will sync when you reconnect.",
        "sync.bannerSignin": "Sign in to the account with pending offline changes.",
        "sync.oneWaiting": "1 change waiting to sync.",
        "sync.changesWaiting": "%d changes waiting to sync.",

        // Search
        "search.title": "Search",
        "search.placeholder": "Contacts, experiences, amounts...",
        "search.quickTitle": "Quick Search",
        "search.quickSubtitle": "Search contacts, shared experiences, descriptions, or transaction amounts.",
        "search.scope.contacts": "Contacts",
        "search.scope.experiences": "Experiences",
        "search.scope.transactions": "Transactions",
        "search.noResults.contacts": "No Contacts Found",
        "search.noResults.experiences": "No Experiences Found",
        "search.noResults.transactions": "No Transactions Found",
        "search.tryDifferent": "Try a different search or switch the filter.",

        // Settings
        "settings.title": "Settings",
        "settings.email": "Email",
        "settings.account": "Tekyida Account",
        "settings.offlineEmail": "Offline: Email cannot be changed while offline.",
        "settings.newEmail": "New email address",
        "settings.confirmEmail": "Confirm new email",
        "settings.changeEmail": "Change Email",
        "settings.emailUpdated": "Email updated successfully.",
        "settings.emailOfflineError": "Cannot change email while offline.",
        "settings.emailInvalid": "Enter a valid email address.",
        "settings.emailMismatch": "Email addresses do not match.",
        "settings.password": "Password",
        "settings.offlinePassword": "Offline: Password cannot be changed while offline.",
        "settings.currentPassword": "Current password",
        "settings.newPassword": "New password (at least 8 characters)",
        "settings.confirmNewPassword": "Confirm new password",
        "settings.changePassword": "Change Password",
        "settings.passwordUpdated": "Password updated successfully.",
        "settings.passwordOfflineError": "Cannot change password while offline.",
        "settings.passwordTooShort": "Password must be at least 8 characters.",
        "settings.passwordMismatch": "Passwords do not match.",
        "settings.preferences": "Preferences",
        "settings.appearance": "Appearance",
        "settings.language": "Language",
        "theme.system": "System",
        "theme.light": "Light",
        "theme.dark": "Dark",
        "settings.hideAmounts": "Hide Amounts on Launch",
        "settings.hideAmountsDesc": "Mask currency figures by default",
        "settings.transferRedirect": "Navigate on Transfer",
        "settings.transferRedirectDesc": "Switch notebook when moving an experience",
        "settings.signOut": "Sign Out",
        "settings.signOutTitle": "Sign Out?",
        "settings.signOutMessage": "You can sign back in to sync your notebooks.",
    ]

    private static let fr: [String: String] = [
        // Common
        "common.cancel": "Annuler",
        "common.delete": "Supprimer",
        "common.done": "Terminé",
        "common.add": "Ajouter",
        "common.create": "Créer",
        "common.ok": "OK",
        "common.saveChanges": "Enregistrer les modifications",
        "common.transaction": "transaction",
        "common.transactions": "transactions",
        "common.archivedSuffix": "(Archivé)",

        // Tabs / App
        "tab.dashboard": "Tableau de bord",
        "tab.experiences": "Expériences",
        "tab.settings": "Paramètres",
        "tab.search": "Rechercher",
        "app.connecting": "Connexion à Tekyida…",
        "app.syncError": "Échec de la synchronisation",

        // Auth
        "auth.verifyTitle": "Vérifiez votre e-mail",
        "auth.welcome": "Bienvenue sur Tekyida",
        "auth.enterCode": "Entrez le code à 6 chiffres envoyé à %@.",
        "auth.signinSubtitle": "Connectez-vous pour synchroniser vos carnets et transactions.",
        "auth.codePlaceholder": "Code de vérification à 6 chiffres",
        "auth.verify": "Vérifier l'e-mail",
        "auth.resend": "Renvoyer le code",
        "auth.backToSignin": "Retour à la connexion",
        "auth.name": "Nom",
        "auth.email": "E-mail",
        "auth.password": "Mot de passe",
        "auth.confirmPassword": "Confirmer le mot de passe",
        "auth.createAccount": "Créer un compte",
        "auth.signIn": "Se connecter",
        "auth.passwordMismatch": "Les mots de passe ne correspondent pas.",
        "auth.passwordTooShort": "Le mot de passe doit contenir au moins 8 caractères.",
        "auth.haveAccount": "J'ai déjà un compte",
        "auth.createOne": "Créer un compte",

        // Dashboard / Contacts
        "contacts.title": "Contacts",
        "contacts.emptyTitle": "Aucun contact",
        "contacts.emptySubtitle": "Ajoutez votre premier contact pour suivre les dettes et prêts.",
        "contacts.add": "Ajouter un Contact",
        "contacts.deleteTitle": "Supprimer le Contact ?",
        "contacts.deleteMessage": "Supprimer '%@' supprimera toutes ses transactions directes.",
        "contact.new": "Nouveau contact",
        "contact.edit": "Modifier le Contact",
        "contact.namePlaceholder": "Nom complet (ex. Sarah Smith)",
        "contact.phonePlaceholder": "Téléphone (optionnel)",
        "contact.save": "Enregistrer le Contact",
        "contact.update": "Mettre à jour le Contact",
        "timeline.title": "Historique d'activité",
        "timeline.emptyTitle": "Aucune transaction",
        "timeline.emptySubtitle": "Touchez le bouton ci-dessous pour ajouter votre première transaction.",

        // Stats
        "stats.moneyOwed": "Argent à Recevoir",
        "stats.moneyGiven": "Argent Donné",
        "stats.netBalance": "Solde Net",

        // Transactions
        "transaction.direction": "Direction",
        "transaction.add": "Ajouter une Transaction",
        "transaction.theyOweYou": "Vous doit",
        "transaction.youOweThem": "Vous devez",
        "transaction.amountPlaceholder": "Montant (ex. 150)",
        "transaction.descriptionPlaceholder": "Description (optionnel)",
        "transaction.notePlaceholder": "Note ou description",
        "transaction.date": "Date",
        "transaction.dateAndTime": "Date & Heure",
        "transaction.edit": "Modifier la Transaction",
        "transaction.deleteTitle": "Supprimer la Transaction ?",

        // Experiences
        "experiences.title": "Expériences",
        "filter.all": "Toutes",
        "filter.active": "Actives",
        "filter.closed": "Clôturées",
        "experiences.openTotal": "Solde Expériences Ouvertes",
        "experiences.emptyTitle": "Aucune expérience",
        "experiences.emptySubtitle": "Regroupez les dépenses et partagez les factures avec des amis grâce aux expériences.",
        "experiences.add": "Ajouter une Expérience",
        "experiences.deleteTitle": "Supprimer l'Expérience ?",
        "experiences.deleteMessage": "Supprimer '%@' supprimera toutes ses transactions.",
        "experience.new": "Nouvelle expérience",
        "experience.edit": "Modifier l'Expérience",
        "experience.namePlaceholder": "Nom de l'expérience (ex. Vacances d'été)",
        "experience.linkedContact": "Contact lié",
        "experience.noContact": "Aucun (expérience autonome)",
        "experience.save": "Enregistrer l'Expérience",
        "experience.update": "Mettre à jour l'Expérience",
        "experience.statusClosed": "Clôturé",
        "experience.statusOpen": "Ouvert",
        "experience.closedNotice": "Cette expérience est clôturée. Rouvrez-la pour faire des modifications.",
        "experience.transactionsTitle": "Transactions",
        "experience.emptyTitle": "Aucune transaction dans cette expérience",
        "experience.emptySubtitle": "Touchez le bouton ci-dessous pour ajouter des dépenses à cette expérience.",

        // Transfer
        "transfer.title": "Transférer l'Expérience",
        "transfer.subtitle": "Déplacer vers un autre carnet",
        "transfer.detail": "Déplacer cette expérience transférera toutes ses transactions. Les contacts sont propres à chaque carnet, le lien avec le contact sera supprimé.",
        "transfer.noOthers": "Aucun autre carnet trouvé. Créez d'abord un autre carnet.",
        "transfer.target": "Carnet de destination",
        "transfer.selectDestination": "Choisir la destination",
        "transfer.confirm": "Confirmer le Transfert",
        "transfer.transfer": "Transférer",

        // Notebooks
        "notebooks.title": "Carnets",
        "notebooks.activeSection": "Carnets Actifs",
        "notebooks.archivedSection": "Carnets Archivés",
        "notebooks.namePlaceholder": "Nom du carnet (max 20)",
        "notebooks.new": "Nouveau Carnet",
        "notebooks.showArchived": "Afficher les archivés (%d)",
        "notebooks.hideArchived": "Masquer les archivés (%d)",
        "notebooks.deleteTitle": "Supprimer le Carnet ?",
        "notebooks.deleteMessage": "Cela supprimera définitivement '%@' et tous ses contacts, expériences et transactions.",
        "notebook.editTitle": "Modifier le Carnet",
        "notebook.nameField": "Nom du carnet",
        "notebook.charLimit": "Les noms de carnets peuvent contenir jusqu'à 20 caractères.",
        "notebook.manage": "Gérer les Carnets",
        "notebook.select": "Choisir un Carnet",

        // Sync
        "sync.syncing": "Synchronisation",
        "sync.offline": "Hors-ligne",
        "sync.pendingCount": "%d en attente",
        "sync.bannerSyncing": "Synchronisation des modifications hors ligne…",
        "sync.bannerOffline": "Hors-ligne. Les modifications seront synchronisées à la reconnexion.",
        "sync.bannerSignin": "Connectez-vous au compte avec des modifications hors ligne en attente.",
        "sync.oneWaiting": "1 modification en attente de synchronisation.",
        "sync.changesWaiting": "%d modifications en attente de synchronisation.",

        // Search
        "search.title": "Rechercher",
        "search.placeholder": "Contacts, expériences, montants…",
        "search.quickTitle": "Recherche rapide",
        "search.quickSubtitle": "Recherchez des contacts, expériences partagées, descriptions ou montants.",
        "search.scope.contacts": "Contacts",
        "search.scope.experiences": "Expériences",
        "search.scope.transactions": "Transactions",
        "search.noResults.contacts": "Aucun contact trouvé",
        "search.noResults.experiences": "Aucune expérience trouvée",
        "search.noResults.transactions": "Aucune transaction trouvée",
        "search.tryDifferent": "Essayez une autre recherche ou changez de filtre.",

        // Settings
        "settings.title": "Paramètres",
        "settings.email": "E-mail",
        "settings.account": "Compte Tekyida",
        "settings.offlineEmail": "Hors-ligne : l'e-mail ne peut pas être modifié hors ligne.",
        "settings.newEmail": "Nouvelle adresse e-mail",
        "settings.confirmEmail": "Confirmer le nouvel e-mail",
        "settings.changeEmail": "Modifier l'e-mail",
        "settings.emailUpdated": "E-mail mis à jour avec succès.",
        "settings.emailOfflineError": "Impossible de modifier l'e-mail hors ligne.",
        "settings.emailInvalid": "Veuillez entrer une adresse e-mail valide.",
        "settings.emailMismatch": "Les adresses e-mail ne correspondent pas.",
        "settings.password": "Mot de passe",
        "settings.offlinePassword": "Hors-ligne : le mot de passe ne peut pas être modifié hors ligne.",
        "settings.currentPassword": "Mot de passe actuel",
        "settings.newPassword": "Nouveau mot de passe (au moins 8 caractères)",
        "settings.confirmNewPassword": "Confirmer le nouveau mot de passe",
        "settings.changePassword": "Modifier le mot de passe",
        "settings.passwordUpdated": "Mot de passe mis à jour avec succès.",
        "settings.passwordOfflineError": "Impossible de modifier le mot de passe hors ligne.",
        "settings.passwordTooShort": "Le mot de passe doit contenir au moins 8 caractères.",
        "settings.passwordMismatch": "Les mots de passe ne correspondent pas.",
        "settings.preferences": "Préférences",
        "settings.appearance": "Apparence",
        "settings.language": "Langue",
        "theme.system": "Système",
        "theme.light": "Clair",
        "theme.dark": "Sombre",
        "settings.hideAmounts": "Masquer les montants au lancement",
        "settings.hideAmountsDesc": "Masquer les montants par défaut",
        "settings.transferRedirect": "Navigation après transfert",
        "settings.transferRedirectDesc": "Changer de carnet lors du déplacement d'une expérience",
        "settings.signOut": "Déconnexion",
        "settings.signOutTitle": "Se déconnecter ?",
        "settings.signOutMessage": "Vous pourrez vous reconnecter pour synchroniser vos carnets.",
    ]
}

func tr(_ key: String) -> String {
    L10n.t(key)
}
