repo_url: "https://mehdirben.github.io/tekyida/fdroid/beta/repo"
repo_name: "Tekyida (Beta)"
repo_icon: "icon.png"
repo_description: "Tekyida Beta Preview Channel"
archive_older: 0
keystore: "keystore.p12"
keystorepass: "tekyidafdroid2026"
keypass: "tekyidafdroid2026"
repo_keyalias: "tekyida"
